apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastfood-db
  template:
    metadata:
      labels:
        app: fastfood-db
    spec:
      containers:
        - name: fastfood-db
          image: mariadb:latest #maycondockeraccount/teste-k8s
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MARIADB_DATABASE
#            - name: MARIADB_DATABASE
#              valueFrom:
#                configMapKeyRef:
#                  name: app-config
#                  key: MARIADB_DATABASE

            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MARIADB_ROOT_PASSWORD

            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MARIADB_USER

            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MARIADB_PASSWORD