apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  TZ: QW1lcmljYS9TYW9fUGF1bG8= #America/Sao_Paulo
  MARIADB_DATABASE: ZmlhcC1mYXN0Zm9vZA== #fiap-fastfood
  MARIADB_ROOT_PASSWORD: cm9vdGZpYXA= #rootfiap
  MARIADB_USER: ZmlhcF9wb3N0ZWNo #fiap_postech
  MARIADB_PASSWORD: ZmlhcA==