apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: maycondockeraccount/fiap-fastfood #alexguimaraes21/fiap-fastfood:latest
          resources:
            requests:
              cpu: "100m" # Solicita 0.1 de um core de CPU
              memory: "128Mi" # Solicita 128 megabytes de memória
            limits:
              cpu: "500m" # Limite de 0.5 de um core de CPU
              memory: "256Mi" # Limite de 256 megabytes de memória
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: TZ

            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATASOURCE_URL

            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATASOURCE_USERNAME

            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATASOURCE_PASSWORD

            - name: DATASOURCE_POOL-NAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATASOURCE_POOL-NAME

            - name: DATASOURCE_MAXIMUM-POOL-SIZE
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATASOURCE_MAXIMUM-POOL-SIZE